### ISSUE TITLE
Code gen bug - missing import for AreaExtensions in CRA

### ISSUE THREAD

**Issue by daltongray** [retejs/rete-kit#2]
Super small bug in the code gen from rete-kit. Using the params below, `AreaExtensions` is not imported from `rete-area-plugin`.  This causes an error in the generated `rete.ts` file whiere AreaExtensions is undefined because it's not imported. 

```
? Name rete-2-example
? Stack (framework) React.js
? Version 18
? Select features React render, Auto arrange, Dataflow engine, Selectable nodes, Context menu
```

**Steps to Reproduce**

- Install the rete-kit globally as per docs
- Run ` rete-kit app --next` and select reactJS as framework, with the features mentioned above.

**Expected behavior**
It all works

**Instead**
There's an error in rete.ts

**Comment by Ni55aN** [comment]
Fixed in [1.0.0-beta.16](https://www.npmjs.com/package/rete-kit/v/1.0.0-beta.16)
